version: "3.8"

services:
  server:
    container_name: server
    image: humansignal/sam:v0
    build:
      context: .
      shm_size: '4gb'
    deploy:
      resources:
        limits:
            memory: 8G
        reservations:
            memory: 4G
    environment:
      # Change this to your model name
      - SAM_CHOICE=MobileSAM
      - LOG_LEVEL=DEBUG
      # Add these variables if you want to access the images stored in Label Studio
      - LABEL_STUDIO_HOST=http://localhost:8080
      - LABEL_STUDIO_ACCESS_TOKEN=5121888a0c607a7a3f4fabdb5c124a5b41c24bd5
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
